version: "3"
services:
 eve_api:
     container_name: eve_api
     build: .
    #  restart: always
     networks:
       - eve-mongo_evenetwork
     volumes:
         - ./src:/app/src
     ports:
       - 5001:5001
networks:
  eve-mongo_evenetwork:
    external: true