version: "3"
services:
 eve_api:
     container_name: eve_api
     build: .
     restart: always
     networks:
       - evemongo_evenetwork
     volumes:
         - .:/app
     ports:
       - 5001:5000
networks:
  evemongo_evenetwork:
    external: true