FROM node

RUN npm install -g react-native-cli
RUN npm install -g create-react-native-app
RUN npm install -g exp
RUN npm install -g expo-cli

RUN mkdir /var/eve-app
WORKDIR /var/eve-app

CMD sleep infinity
