language: pt

pipeline:
- name: "WhitespaceTokenizer"
  intent_split_symbol: "+"
- name: "CRFEntityExtractor"
- name: "DucklingHTTPExtractor"
  url: "http://eve_duckling:8000"
  dimensions: ["time","number"]
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "EmbeddingIntentClassifier"

policies:
  - name: "KerasPolicy"
    max_history: 4
    augmentation_factor: 250
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: "FormPolicy"
  - name: "MappingPolicy"
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.4
    ambiguity_threshold: 0.01
    fallback_action_name: "action_default_fallback"
