language: pt
# pipeline: supervised_embeddings

pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: DucklingHTTPExtractor
  url: "http://eve_duckling:8000"
  dimensions: ["time"]  
  
  
  # locale: "le_BR"
  # timezone: "South America/Brazil"

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.6
    core_threshold: 0.4
    fallback_action_name: action_default_fallback
