version: '3.0'
services:
  eve_nlu_core:
    container_name: eve_nlu_core
    image: eve-core-nlu
    networks:
      - evemongo_evenetwork
    ports:
      - 5005:5005
    volumes:
      - ./core/models:/app/models
      - ./core/config:/app/config
  eve_action_server:
    container_name: eve_action_server
    image: eve-action-server
    networks: 
      - evemongo_evenetwork
    ports:
      - 5055:5055
    volumes:
      - ./action-server/api:/app/api
      - ./action-server/actions:/app/actions
      
networks:
  evemongo_evenetwork:
    external: true

volumes:
  api:
  models:
  config:
  actions:
