version: '3.0'
services:
  eve_core:
    image: evecoreimage
    container_name: eve_core
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    networks:
      - evemongo_evenetwork
  eve_actionserver:
    image: eveactionimage
    container_name: eve_actionserver
    networks:
      - evemongo_evenetwork
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
      - ./api:/app/api

networks:
  evemongo_evenetwork:
    external: true

volumes:
  api:
  actions: