version: '3.0'
services:
  eve_rasa_core:
    container_name: eve_rasa_core
    image: rasa/rasa_core:latest
    ports:
      - 5005:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/
      - --debug
  eve_rasa_nlu:
    container_name: eve_rasa_nlu
    image: rasa/rasa_nlu:latest-tensorflow
    ports:
      - 5000:5000
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models
  eve_action_server:
    container_name: eve_action_server
    image: rasa/rasa_core_sdk:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions

networks:
  evenetwork:

volumes:
  models:
  config:
  rasa_nlu:
  actions:
  db-data:
  mongo-config: