version: '3.0'
services:
  eve_core:
    image: evecoreimage
    container_name: eve-core
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    networks:
      - evemongo_evenetwork
    # command:
    #   - run
    #   - -m
    #   - models/20190522-023305.tar.gz
    #   - --endpoints
    #   - endpoints.yml
    #   - --enable-api
    #   - --debug
  eve_actionserver:
    image: eveactionimage
    container_name: eve-actionserver
    networks:
      - evemongo_evenetwork
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
      - ./api:/app/api

networks:
  evemongo_evenetwork:
    external: true

volumes:
  api:
  actions: