version: '3.0'
services:
  eve_rasa_core:
    container_name: eve_rasa_core
    image: rasa/rasa_core:latest
    networks:
      - evemongo_evenetwork
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models/rasa_core
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/nlu
      - --credentials
      - config/credentials.yml
      - --debug
  eve_rasa_nlu:
    container_name: eve_rasa_nlu
    image: rasa/rasa_nlu:latest-tensorflow
    networks: 
      - evemongo_evenetwork
    ports:
      - 5000:5000
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models
  eve_action_server:
    container_name: eve_action_server
    build: .
    networks: 
      - evemongo_evenetwork
    ports:
      - 5055:5055
    volumes:
      - ./api:/app/api
      - ./actions:/app/actions
      
networks:
  evemongo_evenetwork:
    external: true

volumes:
  api:
  rasa_nlu:
  config:
  actions:
