nlu:
  url: http://localhost:5000
action_endpoint:
  url: http://localhost:5055/webhook
tracker_store:  
        store_type : mongod
        url : dsxxxxxx.mlab.com:xxxxx
        db: evedb
        username : xxxxx
        password : xxxxxxx
        auth_source : evedb