version: '3'
services:
   eve_mongo:
    container_name: eve_mongo
    image: mongo:latest
    networks:
      - evenetwork
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - ./backups:/data/backups
networks:
  evenetwork:
    driver: bridge

volumes:
  backups: