version: "3"
services:
 eve_fup:
     container_name: eve_fup
     build: .
     networks:
       - evemongo_evenetwork
     volumes:
         - ./:/app/
networks:
  evemongo_evenetwork:
    external: true